In [1]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib, os, datetime, sys, os, re
import matplotlib.style as style 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import importlib
%matplotlib inline
#sns.set(style="ticks")
# Making sure that all columns are displyed when we look at data
pd.set_option('display.max_columns', None) 
#style.use('ggplot')
style.use('seaborn')
sns.set(font_scale=1.2)

In [3]:
dataFolder = 'data'
configFolder = 'configs'
runFolder = 'output'
runFolder_GQ = 'output_gq'

# Merging HH and GQ populations

## Reading syntheic data

In [96]:
# reading GQ syn hh as it has Type
hhgq_fname = os.path.join(runFolder_GQ, 'synthetic_households_gq.csv')
hh_fname = os.path.join(runFolder, 'synthetic_households.csv')
hhgq_df = pd.read_csv(hhgq_fname)
hh_df = pd.read_csv(hh_fname)
print('hh_df shape: ', hh_df.shape)
print('hhgq_df shape: ', hhgq_df.shape)

hh_df shape:  (1276612, 10)
hhgq_df shape:  (117058, 11)

In [97]:
# reading GQ syn hh as it has Type
pergq_fname = os.path.join(runFolder_GQ, 'synthetic_persons_gq.csv')
per_fname = os.path.join(runFolder, 'synthetic_persons.csv')
pergq_df = pd.read_csv(pergq_fname)
per_df = pd.read_csv(per_fname)

print('per_df shape: ', per_df.shape)
print('pergq_df shape: ', pergq_df.shape)

# correcting the household id in gq for it to be unique
hhgq_df['household_id'] = len(hh_df) + hhgq_df['household_id']
pergq_df['household_id'] = len(hh_df) + pergq_df['household_id']

# Adding tract to HH GQ and PER GQ
hhgq_df = pd.merge(hhgq_df, geodf[['mgra']], 
                               on = 'mgra', how = 'left')
pergq_df = pd.merge(pergq_df, geodf[['mgra']], 
                               on = 'mgra', how = 'left')

per_df shape:  (3318224, 18)
pergq_df shape:  (117058, 18)

In [98]:
hhfull_df = pd.concat([hh_df, hhgq_df])
hhfull_df = hhfull_df[[item for item in hhfull_df.columns if item not in ['PUMA']]]
print("hhfull_df shape: ", hhfull_df.shape)
hhfull_df.head()

hhfull_df shape:  (1393670, 10)

   household_id  mgra  NP   HHADJINC  HHT  WIF  HUPAC  VEH  BLD  GQ_type
0             1    57   2  975762.00  1.0  2.0    4.0  2.0  2.0      NaN
1             2    57   2   16155.00  3.0  1.0    1.0  1.0  5.0      NaN
2             3    57   3  107053.80  1.0  2.0    1.0  2.0  6.0      NaN
3             4    57   2   40021.32  3.0  1.0    1.0  1.0  1.0      NaN
4             5    57   3   61389.00  3.0  1.0    1.0  2.0  7.0      NaN

In [99]:
hhfull_df['HHADJINC'] = hhfull_df['HHADJINC'].apply(lambda x : x if x > 0 else 0)

In [100]:
perfull_df = pd.concat([per_df, pergq_df])
perfull_df = perfull_df[[item for item in perfull_df.columns if item not in ['PUMA']]]
print("perfull_df shape: ", perfull_df.shape)
perfull_df.head()

perfull_df shape:  (3435282, 17)

,mgra,household_id,SPORDER,AGEP,SEX,ESR,COW,WKHP,SCHG,RAC1P,HISP,MIL,SCHL,OCCP,WKW,NAICS2,SOC2
0,57,1,1,78,1,1.0,1.0,40.0,0,8,1,2.0,24.0,850.0,2.0,11,13
1,57,1,2,81,2,1.0,1.0,40.0,0,1,1,4.0,19.0,2825.0,2.0,11,27
2,57,2,1,29,2,1.0,1.0,36.0,0,1,1,4.0,20.0,3255.0,4.0,62,29
3,57,2,2,1,1,NaN,NaN,NaN,0,9,1,NaN,NaN,NaN,NaN,0,0
4,57,3,1,30,1,1.0,3.0,48.0,0,1,1,4.0,21.0,2320.0,3.0,61,25

In [109]:
hhfull_df['GQ_type'].value_counts()

3.0    43820
1.0    42074
2.0    31164
Name: GQ_type, dtype: int64

In [110]:
perfull_df['ESR'].value_counts()

1.0    1446371
6.0    1028598
3.0     106783
4.0     100370
2.0      36254
5.0        533
Name: ESR, dtype: int64

In [113]:
temp_per = pd.merge(perfull_df, hhfull_df[['household_id', 'GQ_type']], on='household_id' )
temp_per['one'] = 1
temp_per['job_cat'] = None
for i, row in con_set_df1.iterrows():
    j, expr = row['target'], f"{row['expression']}"
    expr = expr.replace('persons', 'temp_per')
    temp_per.loc[pd.eval(expr), 'job_cat'] = j

print("temp_per shape: ", temp_per.shape)
temp_per.head()

temp_per shape:  (3435282, 20)

,mgra,household_id,SPORDER,AGEP,SEX,ESR,COW,WKHP,SCHG,RAC1P,HISP,MIL,SCHL,OCCP,WKW,NAICS2,SOC2,GQ_type,one,job_cat
0,57,1,1,78,1,1.0,1.0,40.0,0,8,1,2.0,24.0,850.0,2.0,11,13,NaN,1,job_3
1,57,1,2,81,2,1.0,1.0,40.0,0,1,1,4.0,19.0,2825.0,2.0,11,27,NaN,1,job_3
2,57,2,1,29,2,1.0,1.0,36.0,0,1,1,4.0,20.0,3255.0,4.0,62,29,NaN,1,job_7
3,57,2,2,1,1,NaN,NaN,NaN,0,9,1,NaN,NaN,NaN,NaN,0,0,NaN,1,None
4,57,3,1,30,1,1.0,3.0,48.0,0,1,1,4.0,21.0,2320.0,3.0,61,25,NaN,1,job_6

# Fixing null values

In [122]:
#na cols
colsnahh = ['HHT', 'HUPAC', "BLD", 'GQ_type']
for col in colsnahh:
    hhfull_df[col] = hhfull_df[col].fillna(0)
hhfull_df.isna().sum()

household_id         0
mgra                 0
NP                   0
HHADJINC             0
HHT                  0
WIF             456142
HUPAC                0
VEH             117058
BLD                  0
GQ_type              0
dtype: int64

In [124]:
#perfull_df[ESR,COW, WKHP, SCHG, MIL, SCHL, OCCP, WKW]
colsnaper = ['ESR', 'COW', 'WKHP', 'SCHG', 'MIL', 'SCHL', 'OCCP', 'WKW']
for col in colsnaper:
    perfull_df[col] = perfull_df[col].fillna(0)
perfull_df.isna().sum()

mgra            0
household_id    0
SPORDER         0
AGEP            0
SEX             0
ESR             0
COW             0
WKHP            0
SCHG            0
RAC1P           0
HISP            0
MIL             0
SCHL            0
OCCP            0
WKW             0
NAICS2          0
SOC2            0
dtype: int64

In [130]:
hhfull_df['GQ_type'].value_counts()

0.0    1276612
3.0      43820
1.0      42074
2.0      31164
Name: GQ_type, dtype: int64

## Writing out full populations
-- save this in the T drive for ABM run

In [131]:
hhfull_df.to_csv(os.path.join(analysisFolder, 'synthetic_households.csv'), index=False)
perfull_df.to_csv(os.path.join(analysisFolder, 'synthetic_persons.csv'), index=False)